### PR TITLE
Update the PCKNibHelper’s NSLayoutConstraints to pass on the identifier and priority.

### PR DESCRIPTION
**Pull request by xtreme-andy-shen**
Turn off auto resizing mask.

As authored by @xtreme-lisheng-tai & @briancroom

### CODE REVIEW

**Comment by akitchen** [comment]
Thanks @xtreme-andy-shen @xtreme-lisheng-tai & @briancroom 

These changes seem more correct and accommodating than what we had recently -- just need to get travis stabilized before we can merge.

Appreciate the pr's and everyone's patience!

**Comment by akitchen** [comment]
I think we're good to merge once Travis passes on master. Hang tight...

**Comment by xtreme-andy-shen** [comment]
👍

**Comment by tjarratt** [comment]
Should we include a small test that verifies we copy over the identifier and priority? It seems to me that change is important, and having a test that documents that happens would be useful if we ever end up wildly refactoring these categories.

**Comment by tjarratt** [comment]
I do want to say that I'm delighted to see these pull requests. You're awesome @xtreme-andy-shen!

**Comment by xtreme-andy-shen** [comment]
@tjarratt Cool, I'll add them

**Comment by xtreme-andy-shen** [comment]
Done.

**Comment by tjarratt** [comment]
Thanks!

**Pull request merged**
