### PR TITLE
Nullability annotations

### PR DESCRIPTION
**Pull request by xtreme-andy-shen**
Rebase and fix of https://github.com/pivotal/PivotalCoreKit/pull/168

Looking to move PCK to better support Swift going forward.

### CODE REVIEW

**Comment by akitchen** [comment]
Awesome, thank you @xtreme-andy-shen !

Will review and merge shortly. Release to follow...

**Comment by xtreme-andy-shen** [comment]
@akitchen thanks! I'm also adding some more functionality coming from other project. Will have PRs for them as well. I'm wondering why Travis fails, I'm running tests locally and it's passing.

**Comment by akitchen** [comment]
We have a large Swift project trying this out today. Separately, I'll have a look at Travis –– I had some trouble with it too around the last release.

**Comment by xtreme-andy-shen** [comment]
@akitchen thanks! Keep me updated, I'm interested, our project is also looking to integrate.

**Comment by akitchen** [comment]
I ran ```rake travis``` locally and it passed. There are only a few places in the code where behavior has been altered, and only subtly ... so I've re-started the travis build and will try to see if we can get to the bottom of it.

**Comment by akitchen** [comment]
So, it appears that there is a race condition behind that failing test, which has only started surfacing as Travis seems to be getting slower and slower for us.

Sorry that your PR drew the short straw here, but we need to fix this before we can push more code to a red CI. I'm looking into the best way to fix it, and am open to any opinions people may have on the subject.

Cc: @tjarratt @younata

**Comment by akitchen** [comment]
Thinking about it a bit further, I'm not sure the assertion that's failing is valid to begin with. The connection is being forced to time out while actively loading data.

I'd be inclined to remove the assertions related to the returned data in the test and move on. Given this is NSURLConnection stuff we should probably be deprecating it anyways.

Thoughts?

**Comment by xtreme-andy-shen** [comment]
@akitchen I'm inclined to remove that as well. Don't see the integrity of the test to be impacted from this removal.

**Comment by akitchen** [comment]
I've added a backlog item to schedule deprecation of the class involved. I think it's a better use of time vs. fixing the race condition or reasoning about the correct expected behavior in the situation under test there.

thanks again for the PR. I'll work through the rest and cut a new release as soon as I can.

**Pull request merged**
