### PR TITLE
Fixes for Xcode 7

### PR DESCRIPTION
**Pull request by briancroom**
- Switch to Cedar's Xcode7 branch for now
- Update the test bundles to use XCTest
- Use a helper WatchKit 1 app target to build the storyboard fixture for the WatchKit specs

### CODE REVIEW

**Comment by briancroom** [comment]
This has now been rebased and tested with Xcode 7 final. I know a couple folks are waiting for this - any objections to merging?

**Comment by akitchen** [comment]
Please, let's merge

**Comment by programmerdave** [comment]
When will the version of PivotalCoreKit be updated so that we can use the XCode7 fixes with cocoapods? Should we be pointing to master in the mean time?

**Comment by akitchen** [comment]
I looked into this briefly today. It looks like the project needs some updates for running one or more of the test suites from the command line before we can cut a new *green release. For the moment master is probably the right place to be.




Please continue to send your pr's and/or issues. Thanks!

**Pull request merged**
