### PR TITLE
Add support for long press on views

### PR DESCRIPTION
**Pull request by philwebster**

### CODE REVIEW

**Comment by briancroom** [comment]
Hey @philwebster, thanks for the contribution! Would you mind adding a corresponding test case to help make sure that this keeps working? https://github.com/pivotal/PivotalCoreKit/blob/master/UIKit/Spec/Extensions/UIViewSpec%2BSpec.mm

**Comment by tjarratt** [comment]
Would love to merge this once we get tests 😻

I'm also happy to answer questions or provide guidance around the PCK tests if that would be helpful. 

Sent From A Very Small Keyboard

**Comment by philwebster** [comment]
Test case added. Thanks!

**Comment by tjarratt** [comment]
This is 🎉 AWESOME 🎉!

Thank you so much @philwebster!

**Pull request merged**
